#!/usr/bin/env bash
# Transfers a file to a server

# Check if less than 4 parameters
if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments
FILE="$1"
IP="$2"
USER="$3"
KEY="$4"

# Use scp to transfer file to remote home directory
scp -o StrictHostKeyChecking=no -i "$KEY" "$FILE" "$USER@$IP:~/"


